### ISSUE TITLE
Plugin Install ERROR

### ISSUE THREAD

**Issue by Fredgod23** [BMathers35/CS2-SteamGroupRestrict#4]
The plugin is not working.
It's not creating the config file and it's not showing up as a plugin in the server console.

**Comment by BMathers35** [comment]
Can you post here the error that the plugin generates in your console when you run your server?

**Comment by Fredgod23** [comment]
It doesn't even install or give me a error, i simply unzip on the "/addons/counterstrikesharp/plugins/" folder but the plugin doesn't do anything.

**Comment by BMathers35** [comment]
Can you try running the plugin manually and see if it prints an error to the server console?

**Comment by Fredgod23** [comment]
Meanwhile i asked a friend to check what was going on and he said that in one of the files , the code was not closed. I dont know where is that error but after that the plugin started to work!

**Comment by BMathers35** [comment]
I will look into it, thanks
